BOARD_READY := 1
BOARD_FAMILY := ecp5
BOARD_STATUS := supported
BOARD_DISPLAY_NAME := ULX3S-85F

BOARD_ASSET_DIR := $(ROOTDIR)/boards/ulx3s

BOARD_YOSYS_SYNTH := synth_ecp5
BOARD_YOSYS_FLAGS :=
BOARD_PNR_TOOL ?= nextpnr-ecp5
BOARD_PNR_FLAGS := --85k --package CABGA381
BOARD_PACK_TOOL ?= ecppack
BOARD_PACK_FLAGS := --idcode 0x41113043
BOARD_PROGRAMMER ?= ujprog
BOARD_PROGRAMMER_FLAGS ?=

COMMON_BSV_DIRS := $(ROOTDIR)/lib/bsv
FPGA_BSV_DIRS := $(ROOTDIR)/fpga/ecp5/bsv
BOARD_BSV_DIRS := $(BOARD_ASSET_DIR)/bsv

COMMON_RTL_DIRS := $(ROOTDIR)/lib/rtl/bsc
FPGA_RTL_DIRS := $(ROOTDIR)/fpga/ecp5/rtl
BOARD_RTL_DIRS := $(BOARD_ASSET_DIR)/rtl

BOARD_CONSTRAINTS := $(BOARD_ASSET_DIR)/constraints/ulx3s.lpf
BOARD_TOP_SOURCE := $(BOARD_ASSET_DIR)/bsv/Top.bsv
BOARD_TOP_MODULE := mkTop
BOARD_BSIM_TOP_SOURCE := $(BOARD_ASSET_DIR)/bsv/Top.bsv
BOARD_BSIM_TOP_MODULE := mkTop_bsim
