ROOTDIR := $(abspath ../..)
PROJECT_NAME := rv32i
TOP_SOURCE := $(CURDIR)/Top.bsv
TOP_MODULE := mkTop
BSIM_TOP_SOURCE := $(CURDIR)/Top.bsv
BSIM_TOP_MODULE := mkTop_bsim
EXTRA_BSV_PATHS := $(CURDIR)/processor
NEEDS_INOUT_FIX := 0
include $(ROOTDIR)/mk/project.mk
